### PR TITLE
Contribution guide and how-to-git guide for CodeNetworkTV project

### PR DESCRIPTION
**Pull request by Lanzafame**
Please review @AdamHibble @texonidas @hjubb @trjstewart

### CODE REVIEW

**Comment by patrickgordon** [comment]
Is gitter the most appropriate? The UQ Slack already exists and I believe they are a part of the Code Network?

**Comment by Lanzafame** [comment]
Yeah but so does the QUT Slack :stuck_out_tongue:. The gitter is also associated purely with the project, indicated by having the same url as the repo. 

Also I have a personal gripe with Slack for open source projects as once you hit the 10k message, you start to lose the history. And I don't see anyone forking out $5 per user.

Also the gitter has been in use for this project from the start so it makes sense to just keep it going.

**Comment by texonidas** [comment]
Looks pretty solid to me. I'm in mobile at the moment so I only have raw, does everything display as intended?

**Comment by Lanzafame** [comment]
@texonidas I believe so. Some links will only display once it is merged because I have preempted what they will be.

**Comment by AdamHibble** [comment]
Looks good :) Go ahead and merge when ready.

**Comment by AdamHibble** [comment]
Regarding Gitter, it is specific to this project, rather than a general chat. :)

**Pull request merged**
